---
version: '3'

services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  wordpress:
    build: .
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - db
      - mailhog
    image: wordpress
    ports:
      - 9030:80
    restart: always
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/basic-contact-form
    working_dir: /var/www/html
  wp-cli:
    image: wordpress:cli
    user: '33:33'
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/mu-plugins/basic-contact-form
      - ./bin/install-wp.sh:/usr/local/bin/install-wp
    links:
      - db
    command: sh -c "sleep 20 && wp core install --path=/var/www/html --url=http://localhost:9030 --title='My Site' --admin_user=wordpress --admin_password=wordpress --admin_email=admin@example.com"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 9031:80
    volumes:
      - /sessions
  composer:
    image: composer
    command: install
    working_dir: /var/www/html
    depends_on:
      - wordpress
    volumes:
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - wordpress:/var/www/html
    links:
      - wordpress:wordpress
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
    - "1025:1025"
    - "8025:8025"
volumes:
  db_data:
  wordpress:
