---
version: '3'

services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
      WP_ENVIRONMENT_TYPE: 'local'
    depends_on:
      - db
      - mailhog
    ports:
      - 8030:80
    restart: always
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/basic-contact-form
      - ./test/fixtures/themes/basic-contact-form:/var/www/html/wp-content/themes/basic-contact-form
      - ./test/fixtures/themes/kicks-app-child:/var/www/html/wp-content/themes/kicks-app-child
      - .uploads:/var/www/html/wp-content/uploads
      - .plugins:/var/www/html/wp-content/plugins
      - .mu-plugins:/var/www/html/wp-content/mu-plugins
    working_dir: /var/www/html
  wp:
    working_dir: /var/www/html
    image: wordpress:cli
    user: '33:33'
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/basic-contact-form
      - ./bin/install-wp.sh:/usr/local/bin/install-wp
      - .uploads:/var/www/html/wp-content/uploads
      - .plugins:/var/www/html/wp-content/plugins
      - .mu-plugins:/var/www/html/wp-content/mu-plugins
    links:
      - db
    command: '--info'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8031:80
    volumes:
      - /sessions
  composer:
    image: composer
    command: install
    working_dir: /var/www/html
    depends_on:
      - wordpress
    volumes:
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - wordpress:/var/www/html
      - .uploads:/var/www/html/wp-content/uploads
      - .plugins:/var/www/html/wp-content/plugins
      - .mu-plugins:/var/www/html/wp-content/mu-plugins
    links:
      - wordpress:wordpress
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
volumes:
  db_data:
  wordpress:
